### ISSUE TITLE
Migrating from FHEM: How to specifiy the enc_key and rolling_code

### ISSUE THREAD

**Issue by cg-ite** [markuzzi/hacs_somfy_cul#1]
Hi,

I'm migrating from FHEM to HA (core installation on dietpi), because of your integration, which is very cool. After I installed your integration, I got the cul working and edited the configure.yaml:
```
cover:
  - platform: somfy_cul
    name: "Wohnzimmer"
    address: "11111F"
    up_time: 20
    down_time: 23

  - platform: somfy_cul
    name: "Küche"
    address: "22222F"
    up_time: 10
    down_time: 13
```
Now I have two shutters in `somfy_cover_state.yaml` and problems to set the right values for the enc_key and rolling_code. 
Which data types should the values have? Are they integers? In FHEM they seem to be hex values like "AB" and "012C".

Greetings, 
Christian
